-- 创建数据库
CREATE DATABASE `app-shield` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';
-- 创建appInfo表
CREATE TABLE `t_app_info` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `APP_NAME` varchar(255) DEFAULT NULL COMMENT 'APP名称',
  `APP_CODE` varchar(255) DEFAULT NULL COMMENT 'APPCODE',
  `APP_KEY` varchar(255) DEFAULT NULL COMMENT 'APPKEY',
  `APP_SECRET` varchar(255) DEFAULT NULL COMMENT 'APP密钥',
  `AES_KEY` varchar(255) DEFAULT NULL COMMENT 'AES密钥',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_USER` varchar(255) DEFAULT NULL COMMENT '创建人',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `UPDATE_USER` varchar(255) DEFAULT NULL COMMENT '更新人',
  `PERMIT_ROLE` varchar(255) DEFAULT NULL COMMENT '权限角色',
  `VALID` int(11) DEFAULT NULL COMMENT '是否有效',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
